CREATE TABLE [DBO].[LOGS]
([ID]              INT IDENTITY(1, 1) NOT NULL, 
 [MESSAGE]         NVARCHAR(MAX) NULL, 
 [MESSAGETEMPLATE] NVARCHAR(MAX) NULL, 
 [LEVEL]           NVARCHAR(128) NULL, 
 [TIMESTAMP]       DATETIME NOT NULL, 
 [EXCEPTION]       NVARCHAR(MAX) NULL, 
 [PROPERTIES]      NVARCHAR(MAX) NULL
                                 CONSTRAINT [PK_LOGS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE ROLE [SERILOGWRITER];

GRANT SELECT ON [DBO].[LOGS] TO [SERILOGWRITER];

GRANT INSERT ON [DBO].[LOGS] TO [SERILOGWRITER];

CREATE LOGIN [SERILOG] WITH PASSWORD = 'password';

CREATE USER [SERILOG] FOR LOGIN [SERILOG] WITH DEFAULT_SCHEMA = DBO;

GRANT CONNECT TO [SERILOG];

ALTER ROLE [SERILOGWRITER] ADD MEMBER [SERILOG];